[34m[1mwandb[0m: [33mWARNING[0m Serializing object of type ndarray that is 4928928 bytes
  0%|                                                                                                                        | 0/670800 [00:00<?, ?it/s]Could not estimate the number of tokens of the input, floating-point operations will not be computed
  0%|                                                                                                         | 1/670800 [02:32<28330:43:32, 152.04s/it]Traceback (most recent call last):
  File "/user/zj2398/femr_chao_meds_v3/src/femr/omop_meds_tutorial/pretrain_motor.py", line 190, in <module>
    main()
  File "/user/zj2398/femr_chao_meds_v3/src/femr/omop_meds_tutorial/pretrain_motor.py", line 183, in main
    train_result = trainer.train(resume_from_checkpoint=args.checkpoint_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/transformers/trainer.py", line 2237, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/transformers/trainer.py", line 2578, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/transformers/trainer.py", line 3840, in training_step
    self.accelerator.backward(loss, **kwargs)
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/accelerate/accelerator.py", line 2578, in backward
    loss.backward(**kwargs)
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/torch/_tensor.py", line 581, in backward
    torch.autograd.backward(
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[rank0]: Traceback (most recent call last):
[rank0]:   File "/user/zj2398/femr_chao_meds_v3/src/femr/omop_meds_tutorial/pretrain_motor.py", line 190, in <module>
[rank0]:     main()
[rank0]:   File "/user/zj2398/femr_chao_meds_v3/src/femr/omop_meds_tutorial/pretrain_motor.py", line 183, in main
[rank0]:     train_result = trainer.train(resume_from_checkpoint=args.checkpoint_dir)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/transformers/trainer.py", line 2237, in train
[rank0]:     return inner_training_loop(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/transformers/trainer.py", line 2578, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/transformers/trainer.py", line 3840, in training_step
[rank0]:     self.accelerator.backward(loss, **kwargs)
[rank0]:   File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/accelerate/accelerator.py", line 2578, in backward
[rank0]:     loss.backward(**kwargs)
[rank0]:   File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/torch/_tensor.py", line 581, in backward
[rank0]:     torch.autograd.backward(
[rank0]:   File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/torch/autograd/__init__.py", line 347, in backward
[rank0]:     _engine_run_backward(
[rank0]:   File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: KeyboardInterrupt
Exception in thread Thread-5 (_pin_memory_loop):
Traceback (most recent call last):
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 59, in _pin_memory_loop
    do_one_step()
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 35, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/site-packages/torch/multiprocessing/reductions.py", line 541, in rebuild_storage_fd
    fd = df.detach()
         ^^^^^^^^^^^
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/multiprocessing/connection.py", line 501, in Client
    c = SocketClient(address)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/user/zj2398/.conda/envs/motor_chao/lib/python3.11/multiprocessing/connection.py", line 629, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
