  0%|                                                                                                       | 0/2012300 [00:00<?, ?it/s]Could not estimate the number of tokens of the input, floating-point operations will not be computed
  0%|                                                                                          | 726/2012300 [01:27<53:44:52, 10.40it/s]Traceback (most recent call last):
  File "/home/zj2398@mc.cumc.columbia.edu/femr_chao_meds_v3/src/femr/omop_meds_tutorial/pretrain_motor.py", line 226, in <module>
    main()
  File "/home/zj2398@mc.cumc.columbia.edu/femr_chao_meds_v3/src/femr/omop_meds_tutorial/pretrain_motor.py", line 219, in main
    train_result = trainer.train(resume_from_checkpoint=args.checkpoint_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception in thread Thread-5 (_pin_memory_loop)  File "/data/anaconda3/envs/motor_chao/lib/python3.11/site-packages/transformers/trainer.py", line 2238, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
:
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/site-packages/transformers/trainer.py", line 2533, in _inner_training_loop
    batch_samples, num_items_in_batch = self.get_batch_samples(epoch_iterator, num_batches, args.device)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/site-packages/transformers/trainer.py", line 5355, in get_batch_samples
    batch_samples.append(next(epoch_iterator))
                         ^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/site-packages/accelerate/data_loader.py", line 579, in __iter__
    next_batch = next(dataloader_iter)
                 ^^^^^^^^^^^^^^^^^^^^^
    self.run()
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/threading.py", line 982, in run
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1448, in _next_data
    idx, data = self._get_data()
                ^^^^^^^^^^^^^^^^
    self._target(*self._args, **self._kwargs)  File "/data/anaconda3/envs/motor_chao/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1402, in _get_data
    success, data = self._try_get_data()
                    ^^^^^^^^^^^^^^^^^^^^

  File "/data/anaconda3/envs/motor_chao/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1243, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 59, in _pin_memory_loop
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/queue.py", line 180, in get
    self.not_empty.wait(remaining)
    do_one_step()  File "/data/anaconda3/envs/motor_chao/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

KeyboardInterrupt
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 35, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/site-packages/torch/multiprocessing/reductions.py", line 541, in rebuild_storage_fd
    fd = df.detach()
         ^^^^^^^^^^^
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/multiprocessing/connection.py", line 519, in Client
    c = SocketClient(address)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/motor_chao/lib/python3.11/multiprocessing/connection.py", line 647, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
